# Version: 2.0

services:

    web:
        container_name: "Web"
        build: "./web"
        restart: "unless-stopped"
        ports:
            - "80:80"
        volumes:
            - "./web/templates:/etc/nginx/templates"
            - "./web/www:/var/www:rw"
        depends_on:
            - "php"
    
    php:
        container_name: "Php"
        build: 
            args:
                user: "joao"
            context: "./php"
            dockerfile: "Dockerfile"
        restart: "unless-stopped"
        volumes:
            - "./web/www:/var/www"
        ports:
            - "9000:9000/tcp"
        depends_on:
            - "db"
            - "redis"

    db:
        container_name: "Db"
        image: "mariadb:latest"
        restart: "unless-stopped"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - "./db/scripts:/docker-entrypoint-initdb.d"
            - "db:/var/lib/mysql"

    phpmyadmin:
        container_name: "PhpMyAdmin"
        image: "phpmyadmin:latest"
        restart: "unless-stopped"
        ports:
            - "8888:80"
        depends_on:
            - "db"
    
    redis:
        container_name: "Redis"
        image: "redis:latest"
        restart: "unless-stopped"
        ports:
            - "6379:6379"

volumes:
    db: